# Generated by Django 4.1.3 on 2022-12-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='aave',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='algorand',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='apecoin',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='avalanche_2',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='axie_infinity',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='binance_usd',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='binancecoin',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='bitcoin',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='bitcoin_cash',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='bitcoin_cash_sv',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cardano',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='chainlink',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cosmos',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='crypto_com_chain',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='dai',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='dogecoin',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='elrond_erd_2',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='eos',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ethereum',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ethereum_classic',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='filecoin',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='flow',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='frax',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hedera_hashgraph',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='internet_computer',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='leo_token',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='lido_dao',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='litecoin',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='matic_network',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='monero',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='near',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='okb',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='polkadot',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='quant_network',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ripple',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='shiba_inu',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='solana',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='staked_ether',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stellar',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='terra_luna',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tether',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tezos',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='the_open_network',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='the_sandbox',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tron',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='trust_wallet_token',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='uniswap',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='usd_coin',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='vechain',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='wrapped_bitcoin',
            field=models.FloatField(default=0, help_text='Volume'),
        ),
    ]
