# Generated by Django 4.1.3 on 2022-12-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_portfolio_aave_portfolio_algorand_portfolio_apecoin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='aave',
            field=models.FloatField(default=0, help_text='Volume', null=True),
        ),
    ]
