# Generated by Django 4.1.3 on 2022-12-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_portfolio_algorand_alter_portfolio_apecoin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='bitcoin',
            field=models.FloatField(default=0, help_text='Volume', null=True, verbose_name='bitcoin'),
        ),
    ]
