# Generated by Django 4.1.3 on 2022-12-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_portfolio_bitcoin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='aave',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='algorand',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='apecoin',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='axie_infinity',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='bitcoin_cash',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='bitcoin_cash_sv',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='cosmos',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='crypto_com_chain',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='elrond_erd_2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='eos',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='ethereum_classic',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='filecoin',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='frax',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='hedera_hashgraph',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='internet_computer',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='lido_dao',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='monero',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='near',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='quant_network',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='stellar',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='terra_luna',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='tezos',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='the_sandbox',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='trust_wallet_token',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='vechain',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='bitcoin',
            field=models.FloatField(default=0, help_text='Volume', null=True),
        ),
    ]
